### ISSUE TITLE
POST - /addusers and /channel response is not JSON

### ISSUE THREAD

**Issue by shangan23** [web-slate/slack-app-clone-api#8]
for the below CURL request the response is not JSON format

**AddUser**
`curl --location --request POST 'https://slackclone001.herokuapp.com/addusers' \
--header 'Content-Type: application/json' \
--data-raw '{
        "username": "udhay-shankar",
        "email": "udhay@gmail.com"
    }'`

**Response**
`User Details Already Exists`

**Add Channel**
`curl --location --request POST 'https://slackclone001.herokuapp.com/channel' \
--header 'Content-Type: application/json' \
--data-raw '  {
    "channel_name": "general",
    "organization_id": "1ae5241e-a51b-11ec-b909-0242ac120002",
    "description": "general channels",
    "is_private": true,
    "members":["1e780ade-a524-11ec-b909-0242ac120002","6ef005fc-a524-11ec-b909-0242ac120002","7f093ecc-a524-11ec-b909-0242ac120002"]
  }'`
  
**Response**
`Channel Name Already Exists`

**Comment by udhaya28** [comment]
Fixed and create new PR.
